name: Flatpak Builder

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flatpak and Build Tools
        run: |
          sudo apt update
          sudo apt install -y flatpak flatpak-builder

      - name: Add Flathub Remote
        run: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
      
      - name: Build Flatpak
        run: flatpak-builder --force-clean build-dir com.bhh32.GuiScaleApplet.yaml

      - name: Create Flatpak Bundle
        run: flatpak build-bundle build-dir gui-scale-applet.flatpak com.bhh32.GuiScaleApplet